### ISSUE TITLE
Software Update Servers no option

### ISSUE THREAD

**Issue by Lotusshaney** [igeekjsc/JSSAPIScripts#3]
Hi, jssMigrationUtility.bash is great but is missing Software Update Servers so without those the Network Segments fail to import into the JSS if a SUS server has been set.

Error: Problem in assignment to software update serve

**Comment by str8outtajc** [comment]
Good catch.  I can add.

**Comment by str8outtajc** [comment]
I tested your code and then merged into main.  Thanks a bunch for that!
